# Generated by Django 3.2.9 on 2021-12-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='lowest_price',
            new_name='price',
        ),
        migrations.AddField(
            model_name='products',
            name='product_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
